### ISSUE TITLE
"Fire" demo. Colors are inverted.

### ISSUE THREAD

**Issue by GunterO** [tuupola/esp-examples#1]
Hello. 
I compiled & uploaded your demo, but the colors seems to be inverted. Any idea why?
I used IDF v4.1 (CMake). Could it be related to that?
![image](https://user-images.githubusercontent.com/7931134/98533805-bd7bcf00-2283-11eb-9cad-8c0c2e3fa4d3.png)

Thanks!

**Comment by tuupola** [comment]
That demo uses really old version of the graphics library, but do a `$ make menuconfig` and change the BGR setting to opposite what you have now.

Now that you reminded me, I will move also the fire effect to [tuupola/esp_effects](https://github.com/tuupola/esp_effects) at some point.

**Comment by GunterO** [comment]
Thank you for your quick answer.
I selected "Invert colors", because deselecting BGR was still giving a white background.
Now everything is as it should be.
And for IDF v4.x, I used the command:
$ idf.py menuconfig
